version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - JWT_SECRET=yourjwtsecret
      - STRIPE_SECRET_KEY=yourstripesecret
    volumes:
      - ./backend:/app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - db
    networks:
      - app_network
  ai-service:
    build:
      context: ./ai-service
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=your_openai_api_key
      - VECTOR_DB_URL=http://chromadb:8000
    volumes:
      - ./ai-service/app:/app/app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - chromadb
    networks:
      - app_network
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    networks:
      - app_network
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    networks:
      - app_network
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - TZ=America/New_York
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/local_workflows
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    user: node
    networks:
      - app_network
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma_data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:
  ollama_data:
  n8n_data:
  chroma_data:
